/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.xavier.csci;

import org.junit.Test;
import static org.junit.Assert.*;

public class CalculatorTest {
    @Test public void calculatorTesting() {
        App tester = new Calculator();
        
        assertEquals(10, tester.add(5,5), "5 + 5 must be 10");
        assertEquals(20, tester.add(5,10,3,2), "5 + 10 + 3 + 2 must be 20");
        assertEquals(0, tester.add(), "error message when no args are provided");
        assertEquals(5, tester.add(5), "5 must be 5");
        
    }
}
